### ISSUE TITLE
Autosave feature

### ISSUE THREAD

**Issue by nerdingasnate** [lejmr/dokuwiki-plugin-drawio#12]
Hi, This is a neat plugin.

Are there any plans to implement some kind of autosave feature as I have managed to lose my diagram changes twice already? :)

**Comment by lejmr** [comment]
Cool idea..  will check that out. The Draw.io provides autosaving itself, so this feature should not be difficult to implement. Maybe just a call as we do with save, but the file name can be slighly altered, so one can guess that this is an autosaved image...

**Comment by lejmr** [comment]
After a brief walkthrough of source code my notes for necessary modifications:

**Detection of on-disk draft**
- https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L40, but _else_ statement need to be used for loading on-disk draft artifact
-  Add API call to find whether is there on-disk saved draft artifact
- The on-disk stored file should contain only the msg.xml portion of data (https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L108)
- The API call can be _get_draft_, and this call can be implemented as _get_ call: https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/action.php#L108
- The _get_draft_ call can be implemented (JS) similarly as we do _get_ call:  https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L67


**Automatic save is supported by handler already**
- https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L108
- https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L114


**Removal of draft**
- Needs to be implemented as a separate API call due to "exit" button that can be pressed after a draft is already created
- https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/script.js#L118


**I dont know when I will get to this feature, but I have to admit I like it.**

**Comment by lejmr** [comment]
Can you please review my autosave functionality? Thanks 

https://github.com/lejmr/dokuwiki-plugin-drawio/pull/13

**Comment by nerdingasnate** [comment]
Hey @lejmr, 

I have applied your changes to my dokuwiki environment and it seems to work pretty good :) 

Thank you !

**Comment by lejmr** [comment]
I did the same. Can you please let me know in a week or so the status update? If all works fine, I will merge it to master and release it as a new stable version.. Thank you

**Comment by nerdingasnate** [comment]
@lejmr just letting you know that it still works great - i think you can merge it in :) thanks

**Comment by lejmr** [comment]
will do
